Add VPC ID to outputs and is_default variable
brucellino/terraform-digitalocean-vpc pull request #64
Opened 2023-12-01 12:13 UTC by dkossako

This commit adds VPC ID to outputs of terraform. ID is required to pass as an input to kubernetes module. `is_default` variable allows to create default projects.

2023-12-20 08:29 UTC, brucellino requested changes
Hello! Thanks very much for the PR - I agree it makes sense to set whether the project created is the default.

Could you perhaps make the minor modifications I suggested in the review?
Thanks!
Bruce

2023-12-20 08:29 UTC, brucellino commented on variables.tf
> +    is_default  = "false"
This is a boolean - could you please update the map with the correct signature to include it?

Furthermore, the default project should be the default, so I would set the default of `is_default` to `true`.
Thanks!

2023-12-20 08:30 UTC, brucellino commented on outputs.tf
LGTM

2024-01-04 13:17 UTC, dkossako commented
Updated

2024-01-04 13:53 UTC, brucellino approved these changes
much obliged!

2024-01-12 15:25 UTC, dkossako commented
There's something wrong with test, but it looks like some token is missing? Or something else?

2024-04-03 04:18 UTC, brucellino commented
Fixed tests, but can't re-run the check. Tested locally. Merging.

2024-04-03 04:19 UTC, merged